default:
  
  # Site name appears at the top of every page
  site_name: "Милеведент"
  
  # Application link at the footer of each page
  app_name: "Bree"
  app_link: "http://adammiribyan.com"

development:
  
  livecss: true
  
production:
  
  livecss: false